// Code generated by validate; DO NOT EDIT.
// github.com/protogodev/validate

package messaging

import (
	"context"

	v "github.com/RussellLuo/validating/v3"
	customvalidator "github.com/protogodev/validate/examples/messaging/customvalidator"
)

func ValidateMiddleware(wrap func(error) error) func(Service) Service {
	return func(next Service) Service {
		if wrap == nil {
			wrap = func(err error) error { return err }
		}
		return validateMiddleware{
			next: next,
			wrap: wrap,
		}
	}
}

type validateMiddleware struct {
	next Service
	wrap func(error) error
}

func (mw validateMiddleware) GetMessage(ctx context.Context, userID string, messageID string) (string, error) {
	schema := v.Schema{
		v.F("userID", userID):       v.LenString(1, 10),
		v.F("messageID", messageID): customvalidator.UUID(),
	}

	if err := v.Validate(schema); err != nil {
		return "", mw.wrap(err)
	}

	return mw.next.GetMessage(ctx, userID, messageID)
}
